# Project: ADS-Project-1
# Makefile created by Dev-C++ 5.15

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = BST.o gen.o main.o splaytree.o project1_AVLtree.o
LINKOBJ  = BST.o gen.o main.o splaytree.o project1_AVLtree.o
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -m64 -g3
INCS     = -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/include" -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/include" -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Program Files (x86)/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ADS-Project-1.exe
CXXFLAGS = $(CXXINCS) -m64 -Wall -g3
CFLAGS   = $(INCS) -m64 -Wall -g3
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

BST.o: BST.cpp
	$(CPP) -c BST.cpp -o BST.o $(CXXFLAGS)

gen.o: gen.cpp
	$(CPP) -c gen.cpp -o gen.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

splaytree.o: splaytree.cpp
	$(CPP) -c splaytree.cpp -o splaytree.o $(CXXFLAGS)

project1_AVLtree.o: project1_AVLtree.cpp
	$(CPP) -c project1_AVLtree.cpp -o project1_AVLtree.o $(CXXFLAGS)
